import { type Href } from 'expo-router';

import { create } from 'zustand';

export enum OnboardingStep {
  Welcome = '1',
  Features = '2',
  Style = '3',
}

export const nudgeStyles = ['gentle', 'normal', 'brutal', 'gamified'] as const;

export type NudgeStyle = (typeof nudgeStyles)[number];

type OnboardingState = {
  nudgeStyle: NudgeStyle;
  completed: boolean;
  setNudgeStyle: (nudgeStyle: NudgeStyle) => void;
  completeOnboarding: () => void;
};

export const useOnboardingStore = create<OnboardingState>((set) => ({
  nudgeStyle: 'normal',
  completed: false,
  setNudgeStyle: (nudgeStyle) => set({ nudgeStyle }),
  completeOnboarding: () => set({ completed: true }),
}));

export function onboardingHref(step: OnboardingStep, style?: NudgeStyle): Href {
  // Typed route unions are generated by Expo and do not include this route until the dev server runs.
  return {
    pathname: '/onboarding/[step]',
    params: style ? { step, style } : { step },
  } as unknown as Href;
}

export function isNudgeStyle(value: string | undefined): value is NudgeStyle {
  return nudgeStyles.some((style) => style === value);
}
