import { useSyncExternalStore } from 'react';

import { type Href } from 'expo-router';

export enum OnboardingStep {
  Welcome = '1',
  Features = '2',
  Style = '3',
}

export const nudgeStyles = ['gentle', 'normal', 'brutal', 'gamified'] as const;

export type NudgeStyle = (typeof nudgeStyles)[number];

type OnboardingState = {
  nudgeStyle: NudgeStyle;
  completed: boolean;
};

let state: OnboardingState = {
  nudgeStyle: 'normal',
  completed: false,
};

const listeners = new Set<() => void>();

function emit() {
  listeners.forEach((listener) => listener());
}

function subscribe(listener: () => void) {
  listeners.add(listener);
  return () => {
    listeners.delete(listener);
  };
}

function getSnapshot() {
  return state;
}

export function onboardingHref(step: OnboardingStep, style?: NudgeStyle): Href {
  // Typed route unions are generated by Expo and do not include this route until the dev server runs.
  return {
    pathname: '/onboarding/[step]',
    params: style ? { step, style } : { step },
  } as unknown as Href;
}

export function isNudgeStyle(value: string | undefined): value is NudgeStyle {
  return nudgeStyles.some((style) => style === value);
}

export function useOnboardingStore<T>(selector: (state: OnboardingState) => T): T {
  const snapshot = useSyncExternalStore(subscribe, getSnapshot, getSnapshot);
  return selector(snapshot);
}

export function setNudgeStyle(nudgeStyle: NudgeStyle) {
  state = { ...state, nudgeStyle };
  emit();
}

export function completeOnboarding() {
  state = { ...state, completed: true };
  emit();
}
